Cotalogue screen
SysoevAndrey/iOS-FakeNFT pull request #43
Opened 2023-06-27 16:20 UTC by KonstantinKirillOff

[Доска](https://github.com/users/SysoevAndrey/projects/1/views/1)
Архитектура - MVVM
Верстка - code

Выполненные задачи
[#1](https://github.com/users/SysoevAndrey/projects/1/views/1?pane=issue&itemId=31129740) - Верстка кастомной ячейки для таблицы
[#2](https://github.com/users/SysoevAndrey/projects/1/views/1?pane=issue&itemId=31129873) - Верстка таблицы с коллекций токенов
[#3](https://github.com/users/SysoevAndrey/projects/1/views/1?pane=issue&itemId=31130043) - Добавление сортировки таблицы по названию
[#4](https://github.com/users/SysoevAndrey/projects/1/views/1?pane=issue&itemId=31130043) - Добавление сортировки таблицы по количеству NFT
https://github.com/SysoevAndrey/iOS-FakeNFT/issues/32 - подключение сетевого слоя к экрану каталога

2023-06-27 17:51 UTC, SysoevAndrey approved these changes
Отличная работа, код легко читается! Оставил несколько комментариев, но среди них нет критических, всё хорошо.
Единственное, что не понял, почему-то странное форматирование, как будто вместо пробелов стоят табы, из-за этого код сильно расширяется)

2023-06-27 17:51 UTC, SysoevAndrey commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueCell.swift
> +	static var defaultReuseIdentifier: String { "collectionListCell" }
Протокол `ReuseIdentifying` и нужен для упрощения работы с коллекциями и таблицами. В данном случае не нужно прописывать идентификатор ячейки, он будет сгенерирован автоматически

2023-06-27 17:51 UTC, SysoevAndrey commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		let cell = tableView.dequeueReusableCell(withIdentifier: CollectionListCell.defaultReuseIdentifier, for: indexPath)
А в этом месте как раз-таки нужно вызвать метод `dequeueReusableCell<T: UICollectionViewCell>(indexPath: IndexPath) -> T`
Пример:
```swift
override func tableView(
    _ tableView: UITableView, 
    cellForRowAt indexPath: IndexPath
) -> UITableViewCell {
    let cell: ProductDetailsTableViewCell = tableView.dequeueReusableCell()
    cell.textLabel?.text = "Ячейка номер \(indexPath.row)"
    return cell
}
```

2023-06-27 17:51 UTC, SysoevAndrey commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		tableView.rowHeight = 187
А почему решил явно задавать высоту ячейки через `rowHeight`, вместо того, чтобы задать констрейнтами высоту картинки, текста и отступа между ними в ячейке?
Это не критика, просто интересно)

2023-06-27 17:51 UTC, SysoevAndrey commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +	private var collectionListViewModel: CollectionListViewModel!
Если можно, то лучше избавиться от force unwrap, там где это возможно. Во ViewController'ах лучше сделать поле опциональным и обращаться к его методам через optinal chaining

2023-06-27 17:51 UTC, SysoevAndrey commented on FakeNFT/Scenes /Catalogue/CatalogueScene/Observable.swift
Лайк за `propertyWrapper` 👍

2023-06-27 17:51 UTC, SysoevAndrey commented on FakeNFT/Services/Requests/GetCollectionByIdRequest.swift
> +	var queryParameters: [String: String]? {
Наверное, `queryParameters` - это не айдишник в данном случае. Id передается в пути url, а query параметры - это фильтры и сортировки, иными словами, то, что идет после `?` в строке url

2023-06-28 05:58 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueCell.swift
> +	static var defaultReuseIdentifier: String { "collectionListCell" }
вот оно что) понял, спасибо! не понял замысел, поторопился

2023-06-28 06:12 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		let cell = tableView.dequeueReusableCell(withIdentifier: CollectionListCell.defaultReuseIdentifier, for: indexPath)
да, разобрался теперь) спасибо!

2023-06-28 06:13 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		tableView.rowHeight = 187
На сколько понял из задания размеры картинку и отступы в зависимости от экрана у нас не меняются, просто срезал угол)

2023-06-28 06:18 UTC, KonstantinKirillOff commented on FakeNFT/Services/Requests/GetCollectionByIdRequest.swift
> +	var queryParameters: [String: String]? {
пересмотрел еще раз Api, ты прав, переделал нa id в строке url

2023-06-28 07:47 UTC, MaximAgarev approved these changes
У меня был только коммент про force unwrap, но его уже дал Андрей :)

2023-07-03 12:56 UTC, IBDesignable commented
@KonstantinKirillOff Привет! Не нашла .md декомпозицию: собери пожалуйста все в список и сложи в корень проекта либо в директорию с документацией.

2023-07-03 14:05 UTC, KonstantinKirillOff commented
Декомпозицию добавил

2023-07-04 19:59 UTC, IBDesignable reviewed
Привет, Константин!

Очень хорошо все сверстано, эпик полноценно собран!
Есть замечания по коду: MVVM не корректно собран и не везде, есть тупиковые состояния из-за ошибки в проектировании асинхронных запросов и игнорирование ошибок от бекенда. С версткой есть несколько небольших замечаний.

2023-07-04 19:59 UTC, IBDesignable commented on Group3_Decomposition.md
> +- Сортировка в корзине - 2 часа
хорошо оформил, только не поняла почему вся декомпозиция попала в твою ветку (тут даже написано что декомпозция твоя, а эпики не твои) 

В идеале в ветке должны храниться изменения касающиеся только задачи – код по задаче, дока по задаче. Здесь это не так, держи в будущем в голове. 

С декомпозицией еще какая штука: идеально чтобы каждый пункт звучал как ответ на вопрос "что надо сделать":  Сверстать ячейку, добавить экран, написать сервис. Чем конкретнее и понятнее написан пункт тем легче его сделать тебе, да и твоему коллеге, если вы планируетесь в паре (такое часто практикуют). 

В целом будет полезно почитать про таймменеджмет у программистов и правила декомпозиции – будет легче и на работе, и на собесах.

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Services/Requests/PutOrderRequest.swift
> +	}
Давай придерживаться такого порядка: свойства, затем функции. 

Инит - это функция, и даже если тут computed-property, они не считаются за функции, и их описывают до них.

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Services/CatalogueDataProvider/CatalogueDataProvider.swift
> +	}
очень странно в гите табы выглядят, а 20ая строчка куда-то совсем уехала. 

Мне больше нравится, когда переносят аргументы начиная с первого, так внутренний уровень будет визуально хорошо считываться. 

```swift
networkClient.send(
    request: getCollectionsRequest,
    type: [Collection].self
)  { result in 
    switch result { ... }
}
```

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +	@Observable private(set) var loadingInProgress: Bool = false
очень хорошо что сетеры закрыл

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +					print(error.localizedDescription)
Такая обработка ошибок не пройдет критерии – нужно с ошибкой что-то сделать: показать алерт, перезапросить данные. В идеале сделать доп задачу с экранами об ошибках

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +					break
лишниц брейк

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +	func addToFavorites(nftViewModel: NFTViewModel) {
Мне не понятно откуда у вьюхи знания про какую-то модель. В идеале она должна тупо передать понятные ей данные - позицию, а доставать модель по этой позиции уже задача вьюмодели. 

Пока не дочитала до конца, возможно не критичное замечание, но есть ощущение что это нарушение направления общения между объектами MVVM

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		viewModel?.nftItems.count ?? 0
Хорошо бы даже такое закрывать интерфейсом: numberOfItems

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		viewModel?.addToCart(nftViewModel: nftItem)
в общем да, вьюконтроллер сходил за данными, вью контроллер дал указания что с с ними делать, а должно быть «"нажата кнопка корзины у элемента X" - сделай с этим что-то»

Никаких запросов данных инициированных вьюхой не должно быть, только "что-то произошло" 
(возьмем как исключение данные для DataSource, обычно просто его реализацию пишут другим объектом)

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		viewModel?.addToCart(nftViewModel: nftItem)
onAddToCart / onAddToFavorites

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +	func setupView() {
очень хорошо что разделяешь блоки с помощью экстеншенов

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +			self.nftCollectionView.reloadData()
тут в одну строку реализация, достаточно вызвать  self?
```suggestion
			self?.nftCollectionView.reloadData()
```

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +	}
не стесняйся писать init, так и от опциональности модели избавишься  и явно задашь ограничение, что этот контроллер без вьюмодели не нужен/не будет работать

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +
Жирноватый класс получился, в таких случаях принято разбивать на подвью

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +		}
а давай этот код вынесем в отдельную вьюшку? 

RatingView - и вся работа по верстке и заполнению будет в ней лежать. На клиенте (ячейке) достаточно будет выставить только число - рейтинг 0...5

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		])
Картинка получилась не квадратной, надо попасть в дизайн-макет
<img width="458" alt="Снимок экрана 2023-07-04 в 22 35 54" src="https://github.com/SysoevAndrey/iOS-FakeNFT/assets/121577115/915ee0f2-7ac0-48d8-b6ab-b5d28b347946">

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +							}
Если придет ошибка, то loadingInProgress никогда не станет false - застрянем на заблокированном экране, придется перезаходить в приложение

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +							countNFTDidLoad += 1
Здесь происходит дичь :)

countNFTDidLoad - локальная переменная, ты захватываешь ее значение и асинхронно пытаешься инкрементировать счетчик, гарантий что не произойдет race condition я тут не вижу. 

Серьезная ошибка, полагаться что запросы уйдут друг за другом и вернутся в том же порядке. Тем более может произойти ошибка, что вообще ломает тут всю логику. 

Подобную задачу обычно решают с помощью [DispatchGroup](https://developer.apple.com/documentation/dispatch/dispatchgroup) расставляя "счетчики задач" и дожидаясь, когда каждая задача выполнится. В учебнике про это было. Нужно вернуться повторить и доделать эти запросы.

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/AboutAuthorViewController.swift
> +
У этого экрана нет ViewModel: проект не пройдет архитектурные критерии

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		collectionVC.initialise(viewModel: collectionVM, model: collection)
```suggestion
		let collectionVM = CollectionViewModel()
		let collectionVC = CollectionViewController(viewModel: collectionVM)
		collectionVC.modalPresentationStyle = .fullScreen
```

В идеале инит у контроллера должен быть такой. Я не понимаю почему еще передается модель в контроллер. Если это Model из MVVM, то ее место только во ViewModel.

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		present(actionSheet, animated: true)
Алерты – тоже контроллеры, им тоже нужен свой небольшой MVVM)

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		tableView.rowHeight = 187
Констрейнтами надо решать :) достаточно правильно настроить размеры содержимого, чтобы ячейка сама могла определять свою высоту. 

Если я все верно поняла – это костыль :) любители костылять на рынке не ценятся 🙌

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +
Почему-то кнопка не отображается 
<img width="458" alt="Снимок экрана 2023-07-04 в 22 48 39" src="https://github.com/SysoevAndrey/iOS-FakeNFT/assets/121577115/183f6ce6-8365-4b4f-b12b-f1be46dbac91">

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +
только нажатое состояние – перепроверь ассеты

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Services/Requests/GetCollectionRequest 2.swift
> +//  GetCollectionRequest.swift
название у файла странное – как будто бы файл удаляли из проекта, но не удалили физически, и тут таких несколько

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Foundation/NetworkClient/NetworkClient.swift
> +		urlRequest.setValue("application/json", forHTTPHeaderField: "Accept")
тут как будто бы табы съехали

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +	}
давай тернарником перепишем? получится короче, даже если вынести получение изображение в отедльную строчку:

let heathIcon= model.isLiked ? UIImage.Icons.likeActive : UIImage.Icons.likeNotActive
heartButton.setImage(heathIcon, for: .normal)

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +	func configure(with model: NFTViewModel, delegate: CollectionNFTCellDelegate) {
Тут кстати отступаешь от MVVM: заводишь делегата и простую тупенькую модель. 

В идеале поручить обработку действий ViewModel, как и инкапсулировать в нее модель данных. 

Любой вьюшных компонент надо постараться рассматривать как MVVM модуль

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Resources/Base.lproj/Main.storyboard
>          </scene>
Таббара для вебвью не должно быть по макетам:
<img width="458" alt="Снимок экрана 2023-07-04 в 22 47 58" src="https://github.com/SysoevAndrey/iOS-FakeNFT/assets/121577115/1110c72e-dc33-4f41-9410-edd921e9f0b7">

2023-07-04 19:59 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +			tableView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 20),
Такой констрейнт будет тебе обрезать таблицу прежде временно. Верстать такую штуку надо от safeArea сверху, но добавлять таблице внутренний отступ контенту. Так скролится будет верно

2023-07-09 08:31 UTC, KonstantinKirillOff commented on Group3_Decomposition.md
> +- Сортировка в корзине - 2 часа
Поправил

2023-07-09 08:48 UTC, KonstantinKirillOff commented on FakeNFT/DesignSystem/Fonts.swift
> +	static let bold22 = UIFont.systemFont(ofSize: 22, weight: .bold)
Перевел табы на пробелы

2023-07-09 09:12 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		tableView.rowHeight = 187
Сделал через констрэйнты

2023-07-09 09:16 UTC, KonstantinKirillOff commented on FakeNFT/Services/Requests/PutOrderRequest.swift
> +	}
Поправил

2023-07-09 09:18 UTC, KonstantinKirillOff commented on FakeNFT/Services/CatalogueDataProvider/CatalogueDataProvider.swift
> +	}
Взял на вооружение, спасибо!

2023-07-09 09:25 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +					break
убрал

2023-07-09 09:42 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +	func addToFavorites(nftViewModel: NFTViewModel) {
да, пересмотрел еще раз, выглядит избыточно, сделал передачу только indexPath

2023-07-09 09:45 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		viewModel?.nftItems.count ?? 0
В данном случае не совсем понял профит, но поправил

2023-07-09 09:47 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		viewModel?.addToCart(nftViewModel: nftItem)
Переделал на передачу indexPath, все остальное делается на стороне VM

2023-07-09 09:50 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +			self.nftCollectionView.reloadData()
Это уже привычка, так научили. Возьму на вооружение

2023-07-09 10:54 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +	}
Да, так действительно проще, спасибо!

2023-07-09 11:07 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +		collectionVC.initialise(viewModel: collectionVM, model: collection)
поправил

2023-07-09 11:12 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +
Можешь привести пример? Не совсем понял как это лучше сделать?

2023-07-09 11:46 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +		}
Вынес в отдельную View

2023-07-09 11:52 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		])
не смог воспроизвести ситуацию
![image](https://github.com/SysoevAndrey/iOS-FakeNFT/assets/53314883/81770576-8047-4ee2-b71d-b7abdfd6e382)

2023-07-09 11:56 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		])
![image](https://github.com/SysoevAndrey/iOS-FakeNFT/assets/53314883/5f50c717-4477-41ea-941c-32a9b7a7f633)

2023-07-09 12:00 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +							}
да, пропустил. Добавил

2023-07-09 12:05 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +
не смог воспроизвести ситуацию, для всех коллекций у каждой ячейки кнопка есть

2023-07-09 12:08 UTC, KonstantinKirillOff commented on FakeNFT/Services/Requests/GetCollectionRequest 2.swift
> +//  GetCollectionRequest.swift
да, странные дубли, нашел и прибил их

2023-07-09 12:09 UTC, KonstantinKirillOff commented on FakeNFT/Foundation/NetworkClient/NetworkClient.swift
> +		urlRequest.setValue("application/json", forHTTPHeaderField: "Accept")
перевел табы на пробелы

2023-07-09 12:14 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +	}
да, так получилось элегантнее)

2023-07-09 12:15 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionNFTCell.swift
> +	func configure(with model: NFTViewModel, delegate: CollectionNFTCellDelegate) {
Я правильно понял, что по хорошему делают VM для ячейки?

2023-07-09 12:17 UTC, KonstantinKirillOff commented on FakeNFT/Resources/Base.lproj/Main.storyboard
>          </scene>
поправил

2023-07-09 12:19 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +			tableView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 20),
понял. поправил

2023-07-10 21:40 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +							countNFTDidLoad += 1
Поправил с помощью DispatchGroup

2023-07-10 21:42 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewModel.swift
> +					print(error.localizedDescription)
Добавил обработку ошибок

2023-07-10 22:13 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/AboutAuthorViewController.swift
> +
Добавил VM для данного экрана

2023-07-14 14:08 UTC, IBDesignable requested changes
Привет! Готова проверка твоей работы, к сожалению не все пункты проходят, поэтому не могу разрешить двигаться дальше на мердж.
[Ревью индивидуального PR Каталог  –  Константин Кириллов.pdf](https://github.com/SysoevAndrey/iOS-FakeNFT/files/12051136/PR.pdf)

Замечания по верстке подкрепляю скриншотами:
<img width="513" alt="Снимок экрана 2023-07-14 в 16 03 56" src="https://github.com/SysoevAndrey/iOS-FakeNFT/assets/121577115/c17bb8ed-43b8-418d-abca-69b6bd647b12">
<img width="797" alt="Снимок экрана 2023-07-14 в 16 03 38" src="https://github.com/SysoevAndrey/iOS-FakeNFT/assets/121577115/175a45fd-efaa-46cc-9191-7bc8617d4d1b">
<img width="799" alt="Снимок экрана 2023-07-14 в 16 03 17" src="https://github.com/SysoevAndrey/iOS-FakeNFT/assets/121577115/c52a1124-c7be-4c54-9173-ed76ee7ad8a4">
<img width="458" alt="Снимок экрана 2023-07-14 в 16 01 05" src="https://github.com/SysoevAndrey/iOS-FakeNFT/assets/121577115/c142ba87-48e2-4f78-b4dd-b861ec5dd10f">

2023-07-16 08:31 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +    private var settingsManager = SettingsManager.shared
менеджера в итоге и реализовал во VM, тут забыл убрать( поправил

2023-07-16 09:29 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/AboutAuthorScreen/AboutAuthorViewController.swift
> +            if self.viewModel.loadingInProgress {
пропустил(

2023-07-16 09:36 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +        viewModel.$loadingInProgress.bind { _ in
пропустил( поправил

2023-07-16 09:38 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +            self.alertPresenter.preparingAlertWithRepeat(alertText: viewModel.mainLoadErrorDescription) {
weak self то добавлен, имеется ввиду обращение к ViewModel без self? Поправил это

2023-07-16 09:40 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +            self.alertPresenter.preparingDataAndDisplay(alertText: viewModel.addToCartErrorDescription){}
закладывал универсальность на будущее, но по Yangi это действительно избыточно, убрал

2023-07-18 19:05 UTC, KonstantinKirillOff commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +        }
Ни я ни команда ни наставник не придумали как это решить через init, данный VC был дан нам на старте проекта и был реализован через сториборд 
все что описано тут, то же самое что мой метод initialize(vm: VM)
https://stackoverflow.com/questions/35315404/custom-init-for-uiviewcontroller-in-swift-with-interface-setup-in-storyboard
Прошу показать пример, как можно было сделать init для VC реализованного через сториборд иначе я голову сломал

2023-07-18 22:02 UTC, KonstantinKirillOff commented
@IBDesignable по поводу отсутствия корзинки попробовал перезалить картинку, саму же проблему не своей локальной версии воспроизвести не могу, как не пытался

2023-07-19 08:28 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +            self.alertPresenter.preparingAlertWithRepeat(alertText: viewModel.mainLoadErrorDescription) {
Где-то на курсе уже сталкивались с двумя вложенными замыканиями. Ты ослабил в одном, затем усилил за счет гварда, и этот уже сильный self передаешь в новый комплишен у preparingAlertWithRepeat. Там тоже нужно переослабить: 
```swift
self.alertPresenter.preparingAlertWithRepeat(alertText: viewModel.mainLoadErrorDescription) { [weak self] in 
self?.viewModel.loadNFTForCollection() 

.... 
}
```

2023-07-19 08:31 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CatalogueScene/CatalogueViewController.swift
> +        }
@KonstantinKirillOff прошу прощения, моя вина. Я почему-то пропустила этот нюанс, в том что экран собран в сториборде. В таком случае мой комментарий полностью невалиден, и все ты делаешь правильно.

Единственное что, я бы все-таки отказалась от нейминга initialise в пользу setup (если метод все еще используется, в прошлое ревью где-то он был не используемым). Все-таки инициализаторы у нас называются init и вводить в заблуждение не стоит

2023-07-19 08:52 UTC, IBDesignable commented
Критичные моменты устранены, Кирилл, спасибо за правки и дополнительные комментарии!

Оставляю на самостоятельные исправления: иконку корзины, еще один слабый селф добавить. По остальным замечаниям – работу принимаю. 

Работу надо смерджить с девелопом и прислать на финальный чек командное решение.

2023-07-19 10:30 UTC, IBDesignable commented on FakeNFT/Scenes /Catalogue/CollectionScene/CollectionViewController.swift
> +		viewModel?.nftItems.count ?? 0
nftItems - если это модель, которая используется для dataSourсe - тоггда действительно избыточно, если это внутряковые данные, то лучше прятать за интерфейсом. 

Хорошо что подходишь к ревью критически)

2023-07-19 14:45 UTC, merged